INTERFACE zif_interface021 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: max length string
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

  METHODS send
    IMPORTING
      body TYPE char2
    RAISING
      cx_static_check.
ENDINTERFACE.
