CLASS ltcl_json DEFINITION FOR TESTING RISK LEVEL HARMLESS DURATION SHORT FINAL.
  PRIVATE SECTION.
    METHODS test FOR TESTING.
ENDCLASS.

CLASS ltcl_json IMPLEMENTATION.
  METHOD test.
    WRITE: / 'hello world'.
  ENDMETHOD.
ENDCLASS.