INTERFACE zif_interface012 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: header parameter
* Description: header parameter
* Version: 1

  CONSTANTS: base_path TYPE string VALUE ''.

  METHODS _something
    IMPORTING
      user_agent TYPE string
    RAISING
      cx_static_check.
ENDINTERFACE.