INTERFACE zif_interface008 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi

* Tag
  TYPES: BEGIN OF tag,
           id TYPE i,
           name TYPE string,
         END OF tag.
* Category
  TYPES: BEGIN OF category,
           id TYPE i,
           name TYPE string,
         END OF category.
* Pet
  TYPES: BEGIN OF pet,
           id TYPE i,
           name TYPE string,
           category TYPE category,
           photourls TYPE STANDARD TABLE OF string WITH DEFAULT KEY,
           tags TYPE STANDARD TABLE OF tag WITH DEFAULT KEY,
         END OF pet.
* response_findpetsbytags
  TYPES response_findpetsbytags TYPE STANDARD TABLE OF pet WITH DEFAULT KEY.

  TYPES: BEGIN OF ret_findpetsbytags,
           _200_app_json TYPE response_findpetsbytags,
           _200_app_xml TYPE response_findpetsbytags,
         END OF ret_findpetsbytags.
  METHODS findpetsbytags
    IMPORTING
      tags TYPE string_table
    RETURNING
      VALUE(return) TYPE ret_findpetsbytags
    RAISING
      cx_static_check.
ENDINTERFACE.