INTERFACE zif_interface008 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi

* Tag
  TYPES: BEGIN OF tag,
           id TYPE i,
           name TYPE string,
         END OF tag.
* Category
  TYPES: BEGIN OF category,
           id TYPE i,
           name TYPE string,
         END OF category.
* Pet
  TYPES: BEGIN OF pet,
           id TYPE i,
           name TYPE string,
           category TYPE category,
           photourls TYPE STANDARD TABLE OF string WITH DEFAULT KEY,
           tags TYPE STANDARD TABLE OF tag WITH DEFAULT KEY,
           status TYPE string,
         END OF pet.
* response_findpetsbystatus
  TYPES response_findpetsbystatus TYPE STANDARD TABLE OF pet WITH DEFAULT KEY.

  TYPES: BEGIN OF ret_findpetsbystatus,
           _200_app_json TYPE response_findpetsbystatus,
           _200_app_xml TYPE ,
         END OF ret_findpetsbystatus.
  METHODS findpetsbystatus
    IMPORTING
      status TYPE string
    RETURNING
      VALUE(return) TYPE ret_findpetsbystatus
    RAISING
      cx_static_check.
ENDINTERFACE.