INTERFACE zif_interface011 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: path parameter
* Description: path parameter
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

  TYPES: BEGIN OF r_foo_param,
           code          TYPE i,
           reason        TYPE string,
         END OF r_foo_param.
  METHODS foo_param
    IMPORTING
      param TYPE string
    RETURNING
      VALUE(return) TYPE r_foo_param
    RAISING
      cx_static_check.
ENDINTERFACE.
