INTERFACE zif_interface024 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: text body
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

* POSTtestRequest
  TYPES: BEGIN OF posttestrequest,
           string1 TYPE timestampl,
         END OF posttestrequest.

  TYPES: BEGIN OF r_send_date_time,
           code          TYPE i,
           reason        TYPE string,
         END OF r_send_date_time.
  METHODS send_date_time
    IMPORTING
      body TYPE posttestrequest
    RETURNING
      VALUE(return) TYPE r_send_date_time
    RAISING
      cx_static_check.
ENDINTERFACE.
