INTERFACE zif_interface025 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test $ref
* Version: 1.0.0

  CONSTANTS base_path TYPE string VALUE ''.

* SafeIdentifier
  TYPES safe_identifier TYPE string.
* BucketConfigurationId
  TYPES bucket_configuration_id TYPE string.
* Error
  TYPES error TYPE string.

  TYPES: BEGIN OF r_search_v2,
           code          TYPE i,
           reason        TYPE string,
           _default_app_json TYPE error,
         END OF r_search_v2.
  "! Search
  METHODS search_v2
    IMPORTING
      config_id TYPE string
    RETURNING
      VALUE(return) TYPE r_search_v2
    RAISING
      cx_static_check.
ENDINTERFACE.
