CLASS zcl_client004 DEFINITION PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
  PUBLIC SECTION.
    INTERFACES zif_interface004.
    METHODS constructor
      IMPORTING
        ii_client TYPE REF TO if_http_client.
  PROTECTED SECTION.
    DATA mi_client TYPE REF TO if_http_client.
ENDCLASS.

CLASS zcl_client004 IMPLEMENTATION.
  METHOD constructor.
    " Use cl_http_client=>create_by_destination or cl_http_client=>create_by_url to create the client
    " the caller must close() the client
    mi_client = ii_client.
  ENDMETHOD.

  METHOD zif_interface004~_test.
    DATA lv_code TYPE i.

    mi_client->request->set_method( 'POST' ).
    mi_client->request->set_data( '112233AABBCCDDEEFF' ).
    mi_client->send( ).
    mi_client->receive( ).

    mi_client->response->get_status( IMPORTING code = lv_code ).
    mi_client->response->get_data( ).
* todo
  ENDMETHOD.

ENDCLASS.