INTERFACE zif_interface004 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: c1_string_concat_table
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

* resultStruct
  TYPES: BEGIN OF result_struct,
           result TYPE f,
         END OF result_struct.
* number1andnumber2
  TYPES: BEGIN OF number1andnumber2,
           number1 TYPE f,
           number2 TYPE f,
         END OF number1andnumber2.
* POSTtestResponse
  TYPES: BEGIN OF subposttestresponse_level_b1,
           level_b11 TYPE STANDARD TABLE OF f WITH DEFAULT KEY,
         END OF subposttestresponse_level_b1.
  TYPES: BEGIN OF posttestresponse,
           level_a1 TYPE STANDARD TABLE OF result_struct WITH DEFAULT KEY,
           level_b1 TYPE subposttestresponse_level_b1,
           level_c1 TYPE f,
         END OF posttestresponse.
* POSTtestRequest
  TYPES: BEGIN OF subposttestrequest_level_b1,
           level_b11 TYPE STANDARD TABLE OF number1andnumber2 WITH DEFAULT KEY,
         END OF subposttestrequest_level_b1.
  TYPES: BEGIN OF posttestrequest,
           level_a1 TYPE STANDARD TABLE OF number1andnumber2 WITH DEFAULT KEY,
           level_b1 TYPE subposttestrequest_level_b1,
           level_c1 TYPE STANDARD TABLE OF f WITH DEFAULT KEY,
         END OF posttestrequest.

  TYPES: BEGIN OF r__test,
           code          TYPE i,
           reason        TYPE string,
           sent_body     TYPE string,
           _200_app_json TYPE posttestresponse,
         END OF r__test.
  METHODS _test
    IMPORTING
      operation TYPE string OPTIONAL
      body TYPE posttestrequest
    RETURNING
      VALUE(return) TYPE r__test
    RAISING
      cx_static_check.
ENDINTERFACE.
