CLASS zcl_icf_serv002 DEFINITION PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: c1_number_add
* Description: c1_number_add
* Version: 1
  PUBLIC SECTION.
    INTERFACES if_http_extension.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_icf_serv002 IMPLEMENTATION.
  METHOD if_http_extension~handle_request.
    DATA li_handler      TYPE REF TO zif_interface002.
    DATA lv_method       TYPE string.
    DATA lv_path         TYPE string.
    CREATE OBJECT li_handler TYPE zcl_icf_impl002.
    lv_path = server->request->get_header_field( '~path' ).
    REPLACE FIRST OCCURRENCE OF zif_interface002=>base_path IN lv_path WITH ''.
    lv_method = server->request->get_method( ).

    TRY.
        IF lv_path = '/test' AND lv_method = 'POST'.
          DATA _test TYPE zif_interface002=>posttestrequest.
          /ui2/cl_json=>deserialize(
            EXPORTING
              json        = server->request->get_cdata( )
              pretty_name = /ui2/cl_json=>pretty_mode-camel_case
            CHANGING
              data        = _test ).
          DATA r__test TYPE zif_interface002=>r__test.
          r__test = li_handler->_test(
            operation = server->request->get_form_field( 'operation' )
            body = _test ).
          server->response->set_content_type( 'application/json' ).
          server->response->set_cdata( /ui2/cl_json=>serialize(
            data        = r__test-_200_app_json
            pretty_name = /ui2/cl_json=>pretty_mode-camel_case ) ).
          server->response->set_status( code = 200 reason = 'OK' ).
          RETURN.
        ENDIF.
      CATCH cx_static_check INTO DATA(lx_error1).
        server->response->set_content_type( 'text/plain' ).
        server->response->set_cdata( lx_error1->get_text( ) ).
        server->response->set_status( code = 500 reason = 'Error' ).
    ENDTRY.

    server->response->set_content_type( 'text/plain' ).
    server->response->set_cdata( |No handler found for { lv_path } { lv_method }| ).
    server->response->set_status( code = 500 reason = 'Error' ).
  ENDMETHOD.
ENDCLASS.
