CLASS zcl_icf_serv032 DEFINITION PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 032
* Description: Operation and schema with the same name, issue 241
* Version: 1.0.0
  PUBLIC SECTION.
    INTERFACES if_http_extension.
    CLASS-METHODS class_constructor.
  PRIVATE SECTION.
    CLASS-DATA mt_name_mappings TYPE /ui2/cl_json=>name_mappings.
ENDCLASS.

CLASS zcl_icf_serv032 IMPLEMENTATION.
  METHOD class_constructor.
  ENDMETHOD.

  METHOD if_http_extension~handle_request.
    DATA li_handler      TYPE REF TO zif_interface032.
    DATA lv_method       TYPE string.
    DATA lv_path         TYPE string.
    CREATE OBJECT li_handler TYPE zcl_icf_impl032.
    lv_path = server->request->get_header_field( '~path' ).
    REPLACE FIRST OCCURRENCE OF zif_interface032=>base_path IN lv_path WITH ''.
    lv_method = server->request->get_method( ).

    TRY.
        IF lv_path = '/scheme' AND lv_method = 'GET'.
          DATA r_get_field_association_sche01 TYPE zif_interface032=>r_get_field_association_sche01.
          r_get_field_association_sche01 = li_handler->get_field_association_sche01( ).
          server->response->set_content_type( 'application/json' ).
          server->response->set_cdata( /ui2/cl_json=>serialize(
            data          = r_get_field_association_sche01-_200_app_json
            pretty_name   = /ui2/cl_json=>pretty_mode-camel_case
            name_mappings = mt_name_mappings ) ).
          server->response->set_status( code = 200 reason = 'OK' ).
          RETURN.
        ENDIF.
      CATCH cx_static_check INTO DATA(lx_error1).
        server->response->set_content_type( 'text/plain' ).
        server->response->set_cdata( lx_error1->get_text( ) ).
        server->response->set_status( code = 500 reason = 'Error' ).
    ENDTRY.

    server->response->set_content_type( 'text/plain' ).
    server->response->set_cdata( |No handler found for { lv_path } { lv_method }| ).
    server->response->set_status( code = 500 reason = 'Error' ).
  ENDMETHOD.
ENDCLASS.
