INTERFACE zif_interface032 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 032
* Description: Operation and schema with the same name, issue 241
* Version: 1.0.0

  CONSTANTS base_path TYPE string VALUE ''.

* GetFieldAssociationScheme
  TYPES: BEGIN OF get_field_association_scheme,
           id TYPE i,
           name TYPE string,
         END OF get_field_association_scheme.

  TYPES: BEGIN OF r_get_field_association_sche01,
           code          TYPE i,
           reason        TYPE string,
           _200_app_json TYPE get_field_association_scheme,
         END OF r_get_field_association_sche01.
  METHODS get_field_association_sche01
    RETURNING
      VALUE(return) TYPE r_get_field_association_sche01
    RAISING
      cx_static_check.
ENDINTERFACE.
