INTERFACE zif_interface029 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 029
* Version: 1.0.0

  CONSTANTS base_path TYPE string VALUE ''.

  TYPES: BEGIN OF r_delete_user,
           code          TYPE i,
           reason        TYPE string,
         END OF r_delete_user.
  "! Delete user by ID
  METHODS delete_user
    IMPORTING
      id TYPE string
    RETURNING
      VALUE(return) TYPE r_delete_user
    RAISING
      cx_static_check.
ENDINTERFACE.
