INTERFACE zif_interface014 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: path summary and description
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

  TYPES: BEGIN OF r_ping_summary,
           code          TYPE i,
           reason        TYPE string,
           sent_body     TYPE string,
         END OF r_ping_summary.
  "! ping summary
  METHODS ping_summary
    RETURNING
      VALUE(return) TYPE r_ping_summary
    RAISING
      cx_static_check.
ENDINTERFACE.
