INTERFACE zif_interface014 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: path summary and description
* Version: 1

  METHODS _ping
    RAISING
      cx_static_check.
ENDINTERFACE.