INTERFACE zif_interface010 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi


  TYPES: BEGIN OF ret_createuser,
           _default_app_json TYPE string,
         END OF ret_createuser.
  METHODS createuser
    RETURNING
      VALUE(return) TYPE ret_createuser
    RAISING
      cx_static_check.
ENDINTERFACE.