INTERFACE zif_interface010 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: default_response
* Description: default_response
* Version: 1.0.11

  CONSTANTS base_path TYPE string VALUE ''.

  TYPES: BEGIN OF r_create_user,
           _default_app_json TYPE string,
         END OF r_create_user.
  METHODS create_user
    IMPORTING
      body TYPE string
    RETURNING
      VALUE(return) TYPE r_create_user
    RAISING
      cx_static_check.
ENDINTERFACE.