INTERFACE zif_interface005 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi

* POSTtestRequest
  TYPES: BEGIN OF posttestrequest,
           string1 TYPE string,
           string2 TYPE string,
         END OF posttestrequest.
* POSTtestResponse
  TYPES: BEGIN OF posttestresponse,
           result TYPE string,
         END OF posttestresponse.

  TYPES: BEGIN OF ret__test,
           200 TYPE posttestresponse,
         END OF ret__test.
  METHODS _test
    IMPORTING
      separator TYPE string
      body TYPE posttestrequest
    RETURNING
      VALUE(return) TYPE ret__test
    RAISING
      cx_static_check.
ENDINTERFACE.