CLASS zcl_icf_serv009 DEFINITION PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: escape name $top
* Description: top dollar sign
* Version: 1
  PUBLIC SECTION.
    INTERFACES if_http_extension.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_icf_serv009 IMPLEMENTATION.
  METHOD if_http_extension~handle_request.
    DATA li_handler      TYPE REF TO zif_interface009.
    DATA lv_method       TYPE string.
    DATA lv_path         TYPE string.
    DATA lv_handler_path TYPE string.

    CREATE OBJECT li_handler TYPE zcl_icf_impl009.
    lv_path = server->request->get_header_field( '~path' ).
    lv_method = server->request->get_method( ).

    TRY.
        CONCATENATE zif_interface009=>base_path '/test' INTO lv_handler_path.
        IF lv_path = lv_handler_path AND lv_method = 'GET'.
          li_handler->_test( server->request->get_form_field( '$top' ) ).
          RETURN.
        ENDIF.
      CATCH cx_static_check.
        server->response->set_content_type( 'text/plain' ).
        server->response->set_cdata( 'exception' ).
        server->response->set_status( code = 500 reason = 'Error' ).
    ENDTRY.

    server->response->set_content_type( 'text/plain' ).
    server->response->set_cdata( 'no handler found' ).
    server->response->set_status( code = 500 reason = 'Error' ).
  ENDMETHOD.
ENDCLASS.