INTERFACE zif_interface009 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: escape name $top
* Description: top dollar sign
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

  TYPES: BEGIN OF r__test,
           code          TYPE i,
           reason        TYPE string,
         END OF r__test.
  METHODS _test
    IMPORTING
      _top TYPE i OPTIONAL
    RETURNING
      VALUE(return) TYPE r__test
    RAISING
      cx_static_check.
ENDINTERFACE.
