INTERFACE zif_interface009 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: escape name $top
* Description: top dollar sign
* Version: 1


  METHODS _test
    IMPORTING
      _top TYPE i OPTIONAL
    RAISING
      cx_static_check.
ENDINTERFACE.