CLASS ltcl_graph DEFINITION FOR TESTING RISK LEVEL HARMLESS DURATION SHORT FINAL.
  PRIVATE SECTION.
    METHODS test FOR TESTING RAISING cx_static_check.
ENDCLASS.

CLASS ltcl_graph IMPLEMENTATION.
  METHOD test.
* todo
  ENDMETHOD.
ENDCLASS.