INTERFACE zif_interface022 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: text body
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

  METHODS send_text
    IMPORTING
      body TYPE string
    RAISING
      cx_static_check.
ENDINTERFACE.
