INTERFACE zif_interface013 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: two path parameters
* Version: 1

  CONSTANTS: base_path TYPE string VALUE ''.

  METHODS _foo_param_another
    IMPORTING
      param TYPE string
      another TYPE string
    RAISING
      cx_static_check.
ENDINTERFACE.