INTERFACE zif_interface006 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: c1_string_concat_object
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

* POSTtestResponse
  TYPES: BEGIN OF subsubposttestresponse_level,
           result TYPE string,
         END OF subsubposttestresponse_level.
  TYPES: BEGIN OF subposttestresponse_level_b1,
           level_b11 TYPE subsubposttestresponse_level,
         END OF subposttestresponse_level_b1.
  TYPES: BEGIN OF subposttestresponse_level_a1,
           result TYPE string,
         END OF subposttestresponse_level_a1.
  TYPES: BEGIN OF posttestresponse,
           level_a1 TYPE subposttestresponse_level_a1,
           level_b1 TYPE subposttestresponse_level_b1,
         END OF posttestresponse.
* POSTtestRequest
  TYPES: BEGIN OF subsubposttestrequest_level_,
           string1 TYPE string,
           string2 TYPE string,
         END OF subsubposttestrequest_level_.
  TYPES: BEGIN OF subposttestrequest_level_b1,
           level_b11 TYPE subsubposttestrequest_level_,
         END OF subposttestrequest_level_b1.
  TYPES: BEGIN OF subposttestrequest_level_a1,
           string1 TYPE string,
           string2 TYPE string,
         END OF subposttestrequest_level_a1.
  TYPES: BEGIN OF posttestrequest,
           level_a1 TYPE subposttestrequest_level_a1,
           level_b1 TYPE subposttestrequest_level_b1,
         END OF posttestrequest.

  TYPES: BEGIN OF r__test,
           code          TYPE i,
           reason        TYPE string,
           _200_app_json TYPE posttestresponse,
         END OF r__test.
  METHODS _test
    IMPORTING
      separator TYPE string OPTIONAL
      body TYPE posttestrequest
    RETURNING
      VALUE(return) TYPE r__test
    RAISING
      cx_static_check.
ENDINTERFACE.
