INTERFACE zif_interface015 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: return structured arrayy
* Version: 1

* Something
  TYPES: BEGIN OF something,
           something TYPE STANDARD TABLE OF  WITH DEFAULT KEY,
         END OF something.

  TYPES: BEGIN OF r__array,
           _200_app_json TYPE something,
         END OF r__array.
  METHODS _array
    RETURNING
      VALUE(return) TYPE r__array
    RAISING
      cx_static_check.
ENDINTERFACE.