CLASS zcl_icf_serv027 DEFINITION PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 027
* Version: 1.0.0
  PUBLIC SECTION.
    INTERFACES if_http_extension.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_icf_serv027 IMPLEMENTATION.
  METHOD if_http_extension~handle_request.
    DATA li_handler      TYPE REF TO zif_interface027.
    DATA lv_method       TYPE string.
    DATA lv_path         TYPE string.
    CREATE OBJECT li_handler TYPE zcl_icf_impl027.
    lv_path = server->request->get_header_field( '~path' ).
    REPLACE FIRST OCCURRENCE OF zif_interface027=>base_path IN lv_path WITH ''.
    lv_method = server->request->get_method( ).

    TRY.
        IF lv_path = '/user/{id}' AND lv_method = 'GET'.
          DATA r_get_user TYPE zif_interface027=>r_get_user.
          r_get_user = li_handler->get_user( server->request->get_form_field( 'todo' ) ).
          server->response->set_content_type( 'application/json' ).
          server->response->set_cdata( /ui2/cl_json=>serialize(
            data        = r_get_user-_200_app_json
            pretty_name = /ui2/cl_json=>pretty_mode-camel_case ) ).
          server->response->set_status( code = 200 reason = 'OK' ).
          RETURN.
        ENDIF.
      CATCH cx_static_check INTO DATA(lx_error1).
        server->response->set_content_type( 'text/plain' ).
        server->response->set_cdata( lx_error1->get_text( ) ).
        server->response->set_status( code = 500 reason = 'Error' ).
    ENDTRY.

    server->response->set_content_type( 'text/plain' ).
    server->response->set_cdata( |No handler found for { lv_path } { lv_method }| ).
    server->response->set_status( code = 500 reason = 'Error' ).
  ENDMETHOD.
ENDCLASS.
