INTERFACE zif_interface027 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 027
* Version: 1.0.0

  CONSTANTS base_path TYPE string VALUE ''.

  TYPES: BEGIN OF r_get_user,
           code          TYPE i,
           reason        TYPE string,
           _200_app_json TYPE string,
         END OF r_get_user.
  "! Get user by ID
  METHODS get_user
    IMPORTING
      id TYPE string
    RETURNING
      VALUE(return) TYPE r_get_user
    RAISING
      cx_static_check.
ENDINTERFACE.
