CLASS zcl_icf_serv026 DEFINITION PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 026
* Version: 1.0.0
  PUBLIC SECTION.
    INTERFACES if_http_extension.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_icf_serv026 IMPLEMENTATION.
  METHOD if_http_extension~handle_request.
    DATA li_handler      TYPE REF TO zif_interface026.
    DATA lv_method       TYPE string.
    DATA lv_path         TYPE string.
    CREATE OBJECT li_handler TYPE zcl_icf_impl026.
    lv_path = server->request->get_header_field( '~path' ).
    REPLACE FIRST OCCURRENCE OF zif_interface026=>base_path IN lv_path WITH ''.
    lv_method = server->request->get_method( ).

    TRY.
        IF lv_path = '/ping' AND lv_method = 'GET'.
          DATA r_ping TYPE zif_interface026=>r_ping.
          r_ping = li_handler->ping( ).
            server->response->set_content_type( 'application/json' ).
            server->response->set_cdata( /ui2/cl_json=>serialize( r_ping-_200_app_json ) ).
            server->response->set_status( code = 200 reason = 'OK' ).
            RETURN.
        ENDIF.
      CATCH cx_static_check INTO DATA(lx_error1).
        server->response->set_content_type( 'text/plain' ).
        server->response->set_cdata( lx_error1->get_text( ) ).
        server->response->set_status( code = 500 reason = 'Error' ).
    ENDTRY.
    TRY.
        IF lv_path = '/echo' AND lv_method = 'POST'.
          DATA r_echo TYPE zif_interface026=>r_echo.
          r_echo = li_handler->echo(
            body = 'todo' ).
            server->response->set_content_type( 'application/json' ).
            server->response->set_cdata( /ui2/cl_json=>serialize( r_echo-_200_app_json ) ).
            server->response->set_status( code = 200 reason = 'OK' ).
            RETURN.
        ENDIF.
      CATCH cx_static_check INTO DATA(lx_error2).
        server->response->set_content_type( 'text/plain' ).
        server->response->set_cdata( lx_error2->get_text( ) ).
        server->response->set_status( code = 500 reason = 'Error' ).
    ENDTRY.

    server->response->set_content_type( 'text/plain' ).
    server->response->set_cdata( |No handler found for { lv_path } { lv_method }| ).
    server->response->set_status( code = 500 reason = 'Error' ).
  ENDMETHOD.
ENDCLASS.
