INTERFACE zif_interface026 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 026
* Version: 1.0.0

  CONSTANTS base_path TYPE string VALUE ''.

  TYPES: BEGIN OF r_ping,
           code          TYPE i,
           reason        TYPE string,
           _200_app_json TYPE string,
         END OF r_ping.
  "! Ping
  METHODS ping
    RETURNING
      VALUE(return) TYPE r_ping
    RAISING
      cx_static_check.
  TYPES: BEGIN OF r_echo,
           code          TYPE i,
           reason        TYPE string,
           _200_app_json TYPE string,
         END OF r_echo.
  "! Echo
  METHODS echo
    IMPORTING
      body TYPE string
    RETURNING
      VALUE(return) TYPE r_echo
    RAISING
      cx_static_check.
ENDINTERFACE.
