CLASS zcl_icf_serv001 DEFINITION PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: ping, no inputs or outputs
* Description: ping
* Version: 1
  PUBLIC SECTION.
    INTERFACES if_http_extension.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_icf_serv001 IMPLEMENTATION.
  METHOD if_http_extension~handle_request.
    DATA li_handler      TYPE REF TO zif_interface001.
    DATA lv_method       TYPE string.
    DATA lv_path         TYPE string.
    CREATE OBJECT li_handler TYPE zcl_icf_impl001.
    lv_path = server->request->get_header_field( '~path' ).
    REPLACE FIRST OCCURRENCE OF zif_interface001=>base_path IN lv_path WITH ''.
    lv_method = server->request->get_method( ).

    TRY.
        IF lv_path = '/ping' AND lv_method = 'POST'.
          DATA r__ping TYPE zif_interface001=>r__ping.
          r__ping = li_handler->_ping( ).
          server->response->set_status( code = 200 reason = 'ping' ).
          RETURN.
        ENDIF.
      CATCH cx_static_check INTO DATA(lx_error1).
        server->response->set_content_type( 'text/plain' ).
        server->response->set_cdata( lx_error1->get_text( ) ).
        server->response->set_status( code = 500 reason = 'Error' ).
    ENDTRY.

    server->response->set_content_type( 'text/plain' ).
    server->response->set_cdata( |No handler found for { lv_path } { lv_method }| ).
    server->response->set_status( code = 500 reason = 'Error' ).
  ENDMETHOD.
ENDCLASS.
