CLASS zcl_icf_impl001 DEFINITION PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_interface001.
ENDCLASS.

CLASS zcl_icf_impl001 IMPLEMENTATION.

  METHOD zif_interface001~_ping.
* todo
  ENDMETHOD.

ENDCLASS.