INTERFACE zif_interface001 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: ping, no inputs or outputs
* Description: ping
* Version: 1


  METHODS _ping
    RAISING
      cx_static_check.
ENDINTERFACE.