INTERFACE zif_interface001 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: ping, no inputs or outputs
* Description: ping
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

  TYPES: BEGIN OF r__ping,
           code          TYPE i,
           reason        TYPE string,
           sent_body     TYPE string,
         END OF r__ping.
  METHODS _ping
    RETURNING
      VALUE(return) TYPE r__ping
    RAISING
      cx_static_check.
ENDINTERFACE.
