CLASS zcl_icf_serv031 DEFINITION PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 031
* Description: Recursive schemas
* Version: 1.0.0
  PUBLIC SECTION.
    INTERFACES if_http_extension.
    CLASS-METHODS class_constructor.
  PRIVATE SECTION.
    CLASS-DATA mt_name_mappings TYPE /ui2/cl_json=>name_mappings.
ENDCLASS.

CLASS zcl_icf_serv031 IMPLEMENTATION.
  METHOD class_constructor.
  ENDMETHOD.

  METHOD if_http_extension~handle_request.
    DATA li_handler      TYPE REF TO zif_interface031.
    DATA lv_method       TYPE string.
    DATA lv_path         TYPE string.
    CREATE OBJECT li_handler TYPE zcl_icf_impl031.
    lv_path = server->request->get_header_field( '~path' ).
    REPLACE FIRST OCCURRENCE OF zif_interface031=>base_path IN lv_path WITH ''.
    lv_method = server->request->get_method( ).

    TRY.
        IF lv_path = '/group' AND lv_method = 'POST'.
          DATA create_group TYPE zif_interface031=>group.
          /ui2/cl_json=>deserialize(
            EXPORTING
              json          = server->request->get_cdata( )
              pretty_name   = /ui2/cl_json=>pretty_mode-camel_case
              name_mappings = mt_name_mappings
            CHANGING
              data          = create_group ).
          DATA r_create_group TYPE zif_interface031=>r_create_group.
          r_create_group = li_handler->create_group(
            body = create_group ).
          server->response->set_content_type( 'application/json' ).
          server->response->set_cdata( /ui2/cl_json=>serialize(
            data          = r_create_group-_200_app_json
            pretty_name   = /ui2/cl_json=>pretty_mode-camel_case
            name_mappings = mt_name_mappings ) ).
          server->response->set_status( code = 200 reason = 'OK' ).
          RETURN.
        ENDIF.
      CATCH cx_static_check INTO DATA(lx_error1).
        server->response->set_content_type( 'text/plain' ).
        server->response->set_cdata( lx_error1->get_text( ) ).
        server->response->set_status( code = 500 reason = 'Error' ).
    ENDTRY.

    server->response->set_content_type( 'text/plain' ).
    server->response->set_cdata( |No handler found for { lv_path } { lv_method }| ).
    server->response->set_status( code = 500 reason = 'Error' ).
  ENDMETHOD.
ENDCLASS.
