INTERFACE zif_interface031 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: Test 031
* Description: Recursive schemas
* Version: 1.0.0

  CONSTANTS base_path TYPE string VALUE ''.

* CompoundClause
  TYPES: BEGIN OF compound_clause,
           operator TYPE string,
           clauses TYPE REF TO data,
         END OF compound_clause.
* Clause
  TYPES: BEGIN OF clause,
           field TYPE string,
           compound TYPE compound_clause,
         END OF clause.
* Group
  TYPES: BEGIN OF group,
           name TYPE string,
           parent TYPE REF TO data,
           children TYPE REF TO data,
         END OF group.

  TYPES: BEGIN OF r_create_group,
           code          TYPE i,
           reason        TYPE string,
           _200_app_json TYPE clause,
         END OF r_create_group.
  METHODS create_group
    IMPORTING
      body TYPE group
    RETURNING
      VALUE(return) TYPE r_create_group
    RAISING
      cx_static_check.
ENDINTERFACE.
