INTERFACE zif_interface007 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi

* resultStruct
  TYPES: BEGIN OF resultstruct,
           result TYPE string,
         END OF resultstruct.
* string1andstring2
  TYPES: BEGIN OF string1andstring2,
           string1 TYPE string,
           string2 TYPE string,
         END OF string1andstring2.
* POSTtestResponse
  TYPES: BEGIN OF subposttestresponse_levelb1,
           levelb11 TYPE STANDARD TABLE OF string WITH DEFAULT KEY, " todo, handle array
         END OF subposttestresponse_levelb1.
  TYPES: BEGIN OF posttestresponse,
           levela1 TYPE STANDARD TABLE OF resultstruct WITH DEFAULT KEY,
           levelb1 TYPE subposttestresponse_levelb1,
           levelc1 TYPE string,
         END OF posttestresponse.
* POSTtestRequest
  TYPES: BEGIN OF subposttestrequest_levelb1,
           levelb11 TYPE STANDARD TABLE OF string1andstring2 WITH DEFAULT KEY,
         END OF subposttestrequest_levelb1.
  TYPES: BEGIN OF posttestrequest,
           levela1 TYPE STANDARD TABLE OF string1andstring2 WITH DEFAULT KEY,
           levelb1 TYPE subposttestrequest_levelb1,
           levelc1 TYPE STANDARD TABLE OF string WITH DEFAULT KEY, " todo, handle array
         END OF posttestrequest.

  TYPES: BEGIN OF ret__test,
           200 TYPE posttestresponse,
         END OF ret__test.
  METHODS _test
    IMPORTING
      separator TYPE string
      body TYPE posttestrequest
    RETURNING
      VALUE(return) TYPE ret__test
    RAISING
      cx_static_check.
ENDINTERFACE.