INTERFACE zif_interface019 PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi
* Title: binary body
* Version: 1

  CONSTANTS base_path TYPE string VALUE ''.

  METHODS send_binary
    RAISING
      cx_static_check.
ENDINTERFACE.