CLASS zcl_aopi_main DEFINITION PUBLIC.
  PUBLIC SECTION.
    TYPES: BEGIN OF ty_result,
        clas TYPE string,
        intf TYPE string,
      END OF ty_result.

    METHODS run
      IMPORTING iv_json TYPE string
      RETURNING VALUE(rs_result) TYPE ty_result.

  PRIVATE SECTION.
    DATA mo_json TYPE REF TO zcl_oapi_json.

    METHODS operations.

ENDCLASS.

CLASS zcl_aopi_main IMPLEMENTATION.

  METHOD run.

    DATA lv_interface_name TYPE string.

    CREATE OBJECT mo_json EXPORTING iv_json = iv_json.

    ASSERT mo_json->value_string( '/openapi' ) CP '3*'.

    operations( ).

    lv_interface_name = 'zif_bar'.

    rs_result-clas =
      |CLASS zcl_bar DEFINITION PUBLIC.\n| &&
      |* Generated by abap-openapi-client\n| &&
      |* { mo_json->value_string( '/info/title' ) }\n| &&
      |  PUBLIC SECTION.\n| &&
      |    INTERFACES { lv_interface_name }.\n| &&
      |ENDCLASS.\n| &&
      |CLASS zcl_bar IMPLEMENTATION.\n| &&
      |ENDCLASS.|.

    rs_result-intf = |INTERFACE { lv_interface_name }.\n| &&
      |* Generated by abap-openapi-client\n| &&
      |* { mo_json->value_string( '/info/title' ) }\n| &&
      |ENDINTERFACE.|.

  ENDMETHOD.

  METHOD operations.
    DATA lt_paths TYPE string_table.
    DATA lv_path LIKE LINE OF lt_paths.

    lt_paths = mo_json->members( '/paths/' ).
    LOOP AT lt_paths INTO lv_path.
      WRITE / lv_path.
    ENDLOOP.
  ENDMETHOD.

ENDCLASS.